from models import Exercise, DifficultyTier, SkillDomain
import uuid

def generate_tab_data(notes, strings=[0, 1, 2, 3, 4, 5]):
    """Generate basic tab data structure"""
    return {
        "notes": notes,
        "time_signature": "4/4",
        "strings": strings
    }

# Timing & Rhythm Exercises
TIMING_EXERCISES = [
    # Beginner
    Exercise(
        id="timing-001",
        title="Quarter Note Foundations",
        domain=SkillDomain.TIMING_RHYTHM,
        subdomain="Basic Subdivisions",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=120,
        bpm_start=60,
        bpm_target=80,
        tags=["metronome", "quarter-notes", "fundamentals"],
        description_training="Train your internal clock to lock with quarter notes.",
        description_why="Quarter notes are the foundation of all rhythm. Mastering this feel makes everything else easier and more musical.",
        steps=["Set metronome to 60 BPM", "Mute strings with left hand", "Strum downstrokes on each click", "Focus on hitting exactly with the click"],
        mistakes_and_fixes=["Rushing ahead of the beat - Take a breath, relax shoulders", "Inconsistent volume - Keep same pick distance from strings"],
        success_criteria={"timing_accuracy": 95, "consistency": 90},
        tab_data=generate_tab_data([{"fret": "x", "string": 5, "beat": 1}, {"fret": "x", "string": 5, "beat": 2}, {"fret": "x", "string": 5, "beat": 3}, {"fret": "x", "string": 5, "beat": 4}])
    ),
    Exercise(
        id="timing-002",
        title="Eighth Note Pulse",
        domain=SkillDomain.TIMING_RHYTHM,
        subdomain="Basic Subdivisions",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=120,
        bpm_start=50,
        bpm_target=70,
        tags=["metronome", "eighth-notes", "subdivision"],
        description_training="Develop feel for eighth note subdivisions.",
        description_why="Eighth notes double your rhythmic vocabulary and are essential for rock, pop, and country strumming.",
        steps=["Set metronome to 50 BPM", "Count '1 and 2 and 3 and 4 and'", "Down on numbers, up on 'and'", "Keep steady even spacing"],
        mistakes_and_fixes=["Uneven spacing - Use a mirror to check stroke consistency", "Tensing up - Shake out hands between reps"],
        success_criteria={"timing_accuracy": 90, "evenness": 85}
    ),
    Exercise(
        id="timing-003",
        title="Accent Practice Level 1",
        domain=SkillDomain.TIMING_RHYTHM,
        subdomain="Dynamics",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=120,
        bpm_start=60,
        bpm_target=80,
        tags=["accents", "dynamics", "control"],
        description_training="Control dynamics by accenting beat 1.",
        description_why="Accents create groove and musical interest. They tell the listener where the beat is.",
        steps=["Play quarter notes at 60 BPM", "Hit beat 1 harder than 2, 3, 4", "Aim for 2x volume on accent", "Keep non-accents consistent"],
        mistakes_and_fixes=["All strokes same volume - Exaggerate accent at first", "Losing tempo when accenting - Practice accent separately"],
        success_criteria={"timing_accuracy": 90, "dynamic_range": 80}
    ),
    # Intermediate
    Exercise(
        id="timing-004",
        title="Sixteenth Note Flow",
        domain=SkillDomain.TIMING_RHYTHM,
        subdomain="Advanced Subdivisions",
        difficulty_tier=DifficultyTier.INTERMEDIATE,
        duration_seconds=180,
        bpm_start=50,
        bpm_target=80,
        tags=["sixteenth-notes", "speed", "control"],
        description_training="Build speed and control with sixteenth notes.",
        description_why="Sixteenth notes unlock funk, metal, and intricate picking patterns.",
        steps=["Start at 50 BPM", "Count '1 e and a 2 e and a'", "Alternate picking throughout", "Build speed in 5 BPM increments"],
        mistakes_and_fixes=["Rushing - Use subdivided metronome at first", "Tension buildup - Stop and stretch every minute"],
        success_criteria={"timing_accuracy": 85, "speed_consistency": 80}
    ),
    Exercise(
        id="timing-005",
        title="Syncopation Study",
        domain=SkillDomain.TIMING_RHYTHM,
        subdomain="Syncopation",
        difficulty_tier=DifficultyTier.INTERMEDIATE,
        duration_seconds=180,
        bpm_start=60,
        bpm_target=90,
        tags=["syncopation", "offbeat", "groove"],
        description_training="Master playing on the off-beats.",
        description_why="Syncopation creates tension and release, making your playing sound professional and groovy.",
        steps=["Play only on 'and' beats", "Keep foot tapping quarter notes", "Feel the push-pull tension", "Gradually increase tempo"],
        mistakes_and_fixes=["Drifting to downbeats - Tap foot louder", "Losing count - Verbalize counts out loud"],
        success_criteria={"timing_accuracy": 85, "groove_feel": 80}
    ),
    Exercise(
        id="timing-006",
        title="Triplet Feel Basics",
        domain=SkillDomain.TIMING_RHYTHM,
        subdomain="Triplets",
        difficulty_tier=DifficultyTier.INTERMEDIATE,
        duration_seconds=180,
        bpm_start=50,
        bpm_target=75,
        tags=["triplets", "shuffle", "blues"],
        description_training="Develop triplet feel for blues and jazz.",
        description_why="Triplets are essential for blues shuffle, jazz swing, and adding sophistication to any style.",
        steps=["Count 'trip-o-let' per beat", "Play 3 notes per click", "Accent first of each group", "Feel the rolling motion"],
        mistakes_and_fixes=["Playing as straight eighth notes - Emphasize middle note delay", "Uneven triplets - Slow down and count carefully"],
        success_criteria={"timing_accuracy": 85, "triplet_evenness": 85}
    ),
    # Advanced
    Exercise(
        id="timing-007",
        title="Polyrhythm 3 Over 4",
        domain=SkillDomain.TIMING_RHYTHM,
        subdomain="Polyrhythms",
        difficulty_tier=DifficultyTier.ADVANCED,
        duration_seconds=240,
        bpm_start=40,
        bpm_target=70,
        tags=["polyrhythm", "independence", "advanced"],
        description_training="Coordinate 3 against 4 polyrhythm.",
        description_why="Polyrhythms appear in progressive rock, jazz fusion, and world music. They expand your rhythmic vocabulary dramatically.",
        steps=["Tap foot in 4", "Play 3 evenly spaced notes", "Use phrase 'pass the golden butter'", "Start extremely slow"],
        mistakes_and_fixes=["Collapsing to simpler rhythm - Isolate each part first", "Foot stopping - Practice foot alone until automatic"],
        success_criteria={"polyrhythm_accuracy": 80, "independence": 75}
    ),
    Exercise(
        id="timing-008",
        title="Metric Modulation",
        domain=SkillDomain.TIMING_RHYTHM,
        subdomain="Advanced Concepts",
        difficulty_tier=DifficultyTier.PRO,
        duration_seconds=300,
        bpm_start=60,
        bpm_target=90,
        tags=["modulation", "tempo", "professional"],
        description_training="Smoothly transition between related tempos.",
        description_why="Metric modulation is used by professional musicians to create seamless tempo changes and sophisticated arrangements.",
        steps=["Establish quarter note pulse", "Shift to treating triplet as new quarter", "New tempo is 1.5x original", "Practice both directions"],
        mistakes_and_fixes=["Jerky transitions - Use overlapping counts", "Losing new tempo - Internalize before transition"],
        success_criteria={"transition_smoothness": 85, "tempo_accuracy": 90}
    ),
]

# Strumming Exercises
STRUMMING_EXERCISES = [
    Exercise(
        id="strum-001",
        title="Basic Down Strum",
        domain=SkillDomain.STRUMMING,
        subdomain="Fundamentals",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=120,
        bpm_start=60,
        bpm_target=90,
        tags=["downstroke", "basic", "acoustic"],
        description_training="Develop consistent downstroke technique.",
        description_why="Clean downstrokes are the foundation of rhythm guitar. Every strumming pattern builds on this.",
        steps=["Hold pick at 45-degree angle", "Strum from wrist, not elbow", "Hit all 6 strings evenly", "Follow through past strings"],
        mistakes_and_fixes=["Strings buzzing - Check left hand pressure", "Uneven volume - Adjust pick angle"],
        success_criteria={"consistency": 90, "tone_quality": 85}
    ),
    Exercise(
        id="strum-002",
        title="Down-Up Pattern",
        domain=SkillDomain.STRUMMING,
        subdomain="Basic Patterns",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=120,
        bpm_start=50,
        bpm_target=80,
        tags=["alternate-strumming", "basic", "essential"],
        description_training="Build fluid alternating strum motion.",
        description_why="Alternating strums double your speed potential and create the rhythmic flow heard in most popular music.",
        steps=["Down on beats, up on 'ands'", "Keep arm moving constantly", "Upstrokes can hit fewer strings", "Maintain steady motion"],
        mistakes_and_fixes=["Arm stopping between strums - Keep pendulum motion", "Upstroke catching - Lighter touch on ups"],
        success_criteria={"timing_accuracy": 90, "fluidity": 85}
    ),
    Exercise(
        id="strum-003",
        title="Folk Strum Pattern",
        domain=SkillDomain.STRUMMING,
        subdomain="Song Patterns",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=180,
        bpm_start=70,
        bpm_target=100,
        tags=["folk", "acoustic", "pattern"],
        description_training="Learn classic D-DU-UDU folk pattern.",
        description_why="This pattern works for thousands of songs and teaches you how rhythmic patterns create musical styles.",
        steps=["Pattern: D - DU UDU", "Down down-up up-down-up", "Accent beats 1 and 3", "Keep arm moving through rests"],
        mistakes_and_fixes=["Losing the pattern - Slow down and count", "No groove feel - Emphasize accents more"],
        success_criteria={"pattern_accuracy": 90, "groove": 80}
    ),
    Exercise(
        id="strum-004",
        title="Rock Power Strum",
        domain=SkillDomain.STRUMMING,
        subdomain="Electric Patterns",
        difficulty_tier=DifficultyTier.INTERMEDIATE,
        duration_seconds=180,
        bpm_start=80,
        bpm_target=120,
        tags=["rock", "electric", "power"],
        description_training="Develop aggressive rock strumming technique.",
        description_why="Rock strumming requires power and precision. This technique drives the energy of rock songs.",
        steps=["Palm mute between strums", "Sharp attack on accents", "Controlled aggression", "Stay relaxed despite power"],
        mistakes_and_fixes=["Tension in shoulder - Reset posture regularly", "Muddy tone - Check muting precision"],
        success_criteria={"attack_quality": 85, "power_control": 85}
    ),
    Exercise(
        id="strum-005",
        title="Funk Scratches",
        domain=SkillDomain.STRUMMING,
        subdomain="Funk Techniques",
        difficulty_tier=DifficultyTier.INTERMEDIATE,
        duration_seconds=180,
        bpm_start=70,
        bpm_target=100,
        tags=["funk", "scratches", "muting"],
        description_training="Master percussive muted scratches.",
        description_why="Funk scratches add percussive texture and make your rhythm playing sound professional and groovy.",
        steps=["Lift fingers to mute strings", "Strum muted strings sharply", "Mix with open chord hits", "Keep wrist loose"],
        mistakes_and_fixes=["Notes ringing through - Press harder to mute", "Scratches too soft - Use more pick"],
        success_criteria={"muting_quality": 90, "rhythm_pocket": 85}
    ),
    Exercise(
        id="strum-006",
        title="Reggae Offbeat",
        domain=SkillDomain.STRUMMING,
        subdomain="Style Patterns",
        difficulty_tier=DifficultyTier.INTERMEDIATE,
        duration_seconds=180,
        bpm_start=65,
        bpm_target=85,
        tags=["reggae", "offbeat", "style"],
        description_training="Develop authentic reggae upstroke feel.",
        description_why="Reggae's signature sound comes from offbeat strumming. This teaches rhythmic space and groove.",
        steps=["Play only on 'and' beats", "Short staccato chords", "Quick release after strum", "Feel the bounce"],
        mistakes_and_fixes=["Chords too long - Release faster", "Missing the pocket - Tap foot on downbeats"],
        success_criteria={"timing_accuracy": 90, "staccato_quality": 85}
    ),
    Exercise(
        id="strum-007",
        title="Dynamic Ballad Strum",
        domain=SkillDomain.STRUMMING,
        subdomain="Dynamics",
        difficulty_tier=DifficultyTier.ADVANCED,
        duration_seconds=240,
        bpm_start=60,
        bpm_target=75,
        tags=["ballad", "dynamics", "expression"],
        description_training="Control volume swells within strumming.",
        description_why="Dynamic control transforms simple strumming into emotional expression. Essential for accompanying singers.",
        steps=["Start soft, build to loud", "Crescendo over 4 bars", "Decrescendo back down", "Never lose tempo control"],
        mistakes_and_fixes=["Tempo changes with volume - Isolate dynamics practice", "Sudden jumps - Smaller gradual changes"],
        success_criteria={"dynamic_range": 90, "tempo_stability": 90}
    ),
]

# Picking Exercises
PICKING_EXERCISES = [
    Exercise(
        id="pick-001",
        title="Single String Alternate",
        domain=SkillDomain.PICKING,
        subdomain="Alternate Picking",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=120,
        bpm_start=60,
        bpm_target=100,
        tags=["alternate", "single-string", "basic"],
        description_training="Build alternate picking foundation on one string.",
        description_why="Alternate picking is the most efficient way to pick fast. Starting on one string isolates the technique.",
        steps=["Pick down-up-down-up on one string", "Keep pick close to string", "Use wrist motion only", "Gradually increase speed"],
        mistakes_and_fixes=["Pick getting stuck - Reduce pick angle", "Using arm instead of wrist - Anchor forearm"],
        success_criteria={"speed": 100, "accuracy": 95},
        tab_data=generate_tab_data([{"fret": 5, "string": 0, "beat": 1, "direction": "down"}, {"fret": 5, "string": 0, "beat": 1.5, "direction": "up"}, {"fret": 5, "string": 0, "beat": 2, "direction": "down"}, {"fret": 5, "string": 0, "beat": 2.5, "direction": "up"}])
    ),
    Exercise(
        id="pick-002",
        title="Two String Crossing",
        domain=SkillDomain.PICKING,
        subdomain="String Crossing",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=120,
        bpm_start=50,
        bpm_target=80,
        tags=["string-crossing", "alternate", "coordination"],
        description_training="Navigate between two adjacent strings smoothly.",
        description_why="String crossing is where most picking breaks down. Master this and scales become much easier.",
        steps=["Alternate between strings 1 and 2", "Keep strict down-up pattern", "Minimize pick movement", "Stay relaxed"],
        mistakes_and_fixes=["Hitting wrong string - Practice without left hand", "Jerky motion - Slow down drastically"],
        success_criteria={"accuracy": 90, "smoothness": 85}
    ),
    Exercise(
        id="pick-003",
        title="Inside Picking",
        domain=SkillDomain.PICKING,
        subdomain="String Crossing",
        difficulty_tier=DifficultyTier.INTERMEDIATE,
        duration_seconds=180,
        bpm_start=50,
        bpm_target=90,
        tags=["inside-picking", "string-crossing", "technique"],
        description_training="Master the challenging inside picking motion.",
        description_why="Inside picking (pick moves between strings) is harder but essential for complex passages.",
        steps=["Down on high string, up on low string", "Pick moves toward body", "Keep motion compact", "Practice slowly with focus"],
        mistakes_and_fixes=["Overshooting strings - Reduce pick depth", "Inconsistent tone - Maintain pick angle"],
        success_criteria={"accuracy": 85, "consistency": 80}
    ),
    Exercise(
        id="pick-004",
        title="Outside Picking",
        domain=SkillDomain.PICKING,
        subdomain="String Crossing",
        difficulty_tier=DifficultyTier.INTERMEDIATE,
        duration_seconds=180,
        bpm_start=50,
        bpm_target=90,
        tags=["outside-picking", "string-crossing", "technique"],
        description_training="Develop outside picking fluency.",
        description_why="Outside picking (pick moves away from strings) feels different and requires separate practice.",
        steps=["Down on low string, up on high string", "Pick moves away from body", "Escape motion is key", "Build gradually"],
        mistakes_and_fixes=["Getting trapped between strings - Exaggerate escape", "Speed plateau - Change practice patterns"],
        success_criteria={"accuracy": 85, "escape_motion": 80}
    ),
    Exercise(
        id="pick-005",
        title="Economy Picking Intro",
        domain=SkillDomain.PICKING,
        subdomain="Economy Picking",
        difficulty_tier=DifficultyTier.INTERMEDIATE,
        duration_seconds=180,
        bpm_start=50,
        bpm_target=85,
        tags=["economy", "sweep", "efficiency"],
        description_training="Learn economy picking for smoother string changes.",
        description_why="Economy picking reduces motion by using the same pick direction when changing strings.",
        steps=["When moving to higher string, use down", "When moving to lower string, use up", "Let pick 'fall' to next string", "Maintain timing"],
        mistakes_and_fixes=["Reverting to strict alternate - Practice consciously", "Uneven timing - Use metronome strictly"],
        success_criteria={"technique_accuracy": 80, "timing": 85}
    ),
    Exercise(
        id="pick-006",
        title="Tremolo Picking",
        domain=SkillDomain.PICKING,
        subdomain="Speed Techniques",
        difficulty_tier=DifficultyTier.ADVANCED,
        duration_seconds=180,
        bpm_start=80,
        bpm_target=160,
        tags=["tremolo", "speed", "endurance"],
        description_training="Build speed with controlled tremolo picking.",
        description_why="Tremolo picking is used in metal, surf, and classical guitar. It builds picking endurance.",
        steps=["Rapid alternate picking on one note", "Start controlled, not max speed", "Stay relaxed", "Build stamina gradually"],
        mistakes_and_fixes=["Tensing up - Take breaks, shake out hands", "Losing control - Reduce speed, focus on clarity"],
        success_criteria={"speed": 140, "control": 85, "endurance": 80}
    ),
    Exercise(
        id="pick-007",
        title="Hybrid Picking Basics",
        domain=SkillDomain.PICKING,
        subdomain="Hybrid Techniques",
        difficulty_tier=DifficultyTier.ADVANCED,
        duration_seconds=240,
        bpm_start=50,
        bpm_target=80,
        tags=["hybrid", "fingers", "country"],
        description_training="Combine pick and fingers for more options.",
        description_why="Hybrid picking opens up patterns impossible with pick alone. Essential for country, fusion, and modern rock.",
        steps=["Hold pick normally", "Use middle finger on higher strings", "Pick bass, finger treble", "Coordinate timing"],
        mistakes_and_fixes=["Weak finger volume - Practice finger alone", "Coordination issues - Separate hands first"],
        success_criteria={"coordination": 80, "volume_balance": 80}
    ),
]

# Fretting Hand Exercises
FRETTING_EXERCISES = [
    Exercise(
        id="fret-001",
        title="Finger Independence 1-2-3-4",
        domain=SkillDomain.FRETTING,
        subdomain="Independence",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=180,
        bpm_start=40,
        bpm_target=80,
        tags=["finger-independence", "chromatic", "warm-up"],
        description_training="Build individual finger control and strength.",
        description_why="Independent fingers mean cleaner chords, faster scales, and better overall technique.",
        steps=["Place all 4 fingers on frets 1-2-3-4", "Lift and replace each finger individually", "Keep other fingers down and still", "Move across all strings"],
        mistakes_and_fixes=["Fingers flying up - Keep close to fretboard", "Other fingers moving - Slow down, focus"],
        success_criteria={"independence": 85, "finger_proximity": 80}
    ),
    Exercise(
        id="fret-002",
        title="Spider Walk",
        domain=SkillDomain.FRETTING,
        subdomain="Coordination",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=180,
        bpm_start=40,
        bpm_target=70,
        tags=["spider", "coordination", "classic"],
        description_training="Classic exercise for finger coordination.",
        description_why="The spider walk trains finger independence while adding string changes. A guitarist's essential warm-up.",
        steps=["Frets 1-2-3-4 on string 6", "Shift to string 5, offset pattern", "Continue across all strings", "Reverse direction"],
        mistakes_and_fixes=["Losing position - Watch fret markers", "Inconsistent pressure - Focus on tone quality"],
        success_criteria={"accuracy": 90, "evenness": 85}
    ),
    Exercise(
        id="fret-003",
        title="Stretch Building",
        domain=SkillDomain.FRETTING,
        subdomain="Stretching",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=180,
        bpm_start=40,
        bpm_target=60,
        tags=["stretch", "flexibility", "reach"],
        description_training="Gradually increase finger span safely.",
        description_why="Better stretch means easier chord voicings and scale patterns. Build slowly to avoid injury.",
        steps=["Start with comfortable 4-fret span", "Add one fret of stretch", "Hold position 10 seconds", "Never force to pain"],
        mistakes_and_fixes=["Pain or discomfort - Reduce stretch immediately", "Thumb position wrong - Keep thumb behind neck"],
        success_criteria={"stretch_range": 80, "comfort": 90}
    ),
    Exercise(
        id="fret-004",
        title="Position Shifts",
        domain=SkillDomain.FRETTING,
        subdomain="Shifting",
        difficulty_tier=DifficultyTier.INTERMEDIATE,
        duration_seconds=180,
        bpm_start=50,
        bpm_target=80,
        tags=["shifting", "position", "neck-knowledge"],
        description_training="Develop smooth position changes up and down the neck.",
        description_why="Position shifts are essential for playing beyond first position and accessing the entire fretboard.",
        steps=["Play pattern at fret 1", "Shift smoothly to fret 5", "Maintain finger shape during shift", "Use guide finger"],
        mistakes_and_fixes=["Jerky shifts - Lead with thumb", "Notes in between - Lift cleanly before shift"],
        success_criteria={"shift_smoothness": 85, "accuracy": 90}
    ),
    Exercise(
        id="fret-005",
        title="Finger Rolling",
        domain=SkillDomain.FRETTING,
        subdomain="Advanced Control",
        difficulty_tier=DifficultyTier.ADVANCED,
        duration_seconds=180,
        bpm_start=40,
        bpm_target=70,
        tags=["rolling", "barre", "advanced"],
        description_training="Roll finger across strings at same fret.",
        description_why="Finger rolling prevents note bleed in complex chords and arpeggios. It's how pros play cleanly.",
        steps=["Barre two strings at same fret", "Roll finger to mute one while playing other", "Control which note rings", "Practice slowly"],
        mistakes_and_fixes=["Both notes ringing - Adjust finger pressure point", "Neither note clean - Find the balance angle"],
        success_criteria={"control": 80, "clean_separation": 85}
    ),
]

# Chords & Harmony Exercises  
CHORD_EXERCISES = [
    Exercise(
        id="chord-001",
        title="Open E Major",
        domain=SkillDomain.CHORDS,
        subdomain="Open Chords",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=120,
        bpm_start=40,
        bpm_target=80,
        tags=["open-chord", "major", "essential"],
        description_training="Master the E major open chord shape.",
        description_why="E major is one of the most used chords in guitar. Its shape also becomes the basis for barre chords.",
        steps=["Index on G string fret 1", "Middle on A string fret 2", "Ring on D string fret 2", "Strum all 6 strings"],
        mistakes_and_fixes=["Muted strings - Check finger position, arch fingers", "Buzzing - Press closer to fret"],
        success_criteria={"clarity": 95, "chord_speed": 80}
    ),
    Exercise(
        id="chord-002",
        title="Open A Major",
        domain=SkillDomain.CHORDS,
        subdomain="Open Chords",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=120,
        bpm_start=40,
        bpm_target=80,
        tags=["open-chord", "major", "essential"],
        description_training="Master the A major open chord shape.",
        description_why="A major is essential for countless songs and its shape is the basis for other chord types.",
        steps=["Index, middle, ring on fret 2", "D, G, B strings respectively", "Don't play low E string", "Strum from A string down"],
        mistakes_and_fixes=["High E muted - Adjust finger angles", "Fingers crowded - Try different finger arrangement"],
        success_criteria={"clarity": 95, "chord_speed": 80}
    ),
    Exercise(
        id="chord-003",
        title="Open D Major",
        domain=SkillDomain.CHORDS,
        subdomain="Open Chords",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=120,
        bpm_start=40,
        bpm_target=80,
        tags=["open-chord", "major", "essential"],
        description_training="Master the D major open chord shape.",
        description_why="D major completes the most basic chord set and introduces a new hand position.",
        steps=["Index on G string fret 2", "Ring on B string fret 3", "Middle on high E fret 2", "Strum top 4 strings only"],
        mistakes_and_fixes=["Low strings ringing - Mute with thumb or avoid", "Stretch uncomfortable - Position thumb lower"],
        success_criteria={"clarity": 95, "chord_speed": 80}
    ),
    Exercise(
        id="chord-004",
        title="E-A-D Chord Changes",
        domain=SkillDomain.CHORDS,
        subdomain="Transitions",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=180,
        bpm_start=40,
        bpm_target=70,
        tags=["chord-changes", "transitions", "essential"],
        description_training="Build speed switching between E, A, and D.",
        description_why="Smooth chord changes are what separate beginners from intermediate players. This is fundamental.",
        steps=["Play E for 4 beats", "Change to A on beat 1", "Play A for 4 beats", "Change to D, then back to E"],
        mistakes_and_fixes=["Changes too slow - Look ahead, prepare fingers", "Losing rhythm - Simplify strum during change"],
        success_criteria={"change_speed": 80, "continuity": 85}
    ),
    Exercise(
        id="chord-005",
        title="Minor Chord Intro: Am, Em, Dm",
        domain=SkillDomain.CHORDS,
        subdomain="Minor Chords",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=180,
        bpm_start=40,
        bpm_target=70,
        tags=["minor", "open-chord", "emotional"],
        description_training="Learn the three essential open minor chords.",
        description_why="Minor chords add emotional depth. Am, Em, Dm are used in virtually every style of music.",
        steps=["Learn Am shape (A major minus one finger)", "Learn Em shape (E major minus one finger)", "Learn Dm shape", "Practice changing between them"],
        mistakes_and_fixes=["Confusing with major shapes - Note the one-finger difference", "Wrong bass note - Check which strings to strum"],
        success_criteria={"accuracy": 90, "change_speed": 75}
    ),
    Exercise(
        id="chord-006",
        title="Power Chord Fundamentals",
        domain=SkillDomain.CHORDS,
        subdomain="Power Chords",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=180,
        bpm_start=60,
        bpm_target=100,
        tags=["power-chord", "rock", "electric"],
        description_training="Master the moveable power chord shape.",
        description_why="Power chords are the sound of rock. They're moveable, easy, and sound huge with distortion.",
        steps=["Root on low E with index", "Fifth two frets up with ring", "Mute other strings", "Move shape anywhere"],
        mistakes_and_fixes=["Other strings ringing - Angle index to mute", "Weak sound - Press firmly, check position"],
        success_criteria={"muting": 90, "power": 85}
    ),
    Exercise(
        id="chord-007",
        title="Barre Chord: F Major",
        domain=SkillDomain.CHORDS,
        subdomain="Barre Chords",
        difficulty_tier=DifficultyTier.INTERMEDIATE,
        duration_seconds=240,
        bpm_start=30,
        bpm_target=60,
        tags=["barre", "major", "challenge"],
        description_training="Conquer the F major barre chord.",
        description_why="F major is often the first major hurdle for guitarists. Mastering it unlocks all major barre chords.",
        steps=["Barre all strings at fret 1", "Add E major shape above barre", "Press close to fret", "Use arm strength, not just finger"],
        mistakes_and_fixes=["Muted notes - Roll barre slightly, check each string", "Hand fatigue - Take breaks, build strength gradually"],
        success_criteria={"clarity": 85, "stamina": 75}
    ),
    Exercise(
        id="chord-008",
        title="Seventh Chord Intro",
        domain=SkillDomain.CHORDS,
        subdomain="Extended Chords",
        difficulty_tier=DifficultyTier.INTERMEDIATE,
        duration_seconds=180,
        bpm_start=40,
        bpm_target=70,
        tags=["7th-chords", "jazz", "blues"],
        description_training="Learn essential seventh chord voicings.",
        description_why="Seventh chords add color and sophistication. They're essential for blues, jazz, and R&B.",
        steps=["Learn A7, E7, D7 open shapes", "Notice the 'bluesy' sound", "Use in a 12-bar blues", "Feel the pull to resolve"],
        mistakes_and_fixes=["Mixing up shapes - Practice one at a time", "Not hearing the difference - Compare to regular major"],
        success_criteria={"accuracy": 85, "musicality": 80}
    ),
    Exercise(
        id="chord-009",
        title="Triads on Top 3 Strings",
        domain=SkillDomain.CHORDS,
        subdomain="Triads",
        difficulty_tier=DifficultyTier.ADVANCED,
        duration_seconds=240,
        bpm_start=40,
        bpm_target=70,
        tags=["triads", "voicings", "theory"],
        description_training="Map major and minor triads on strings 1-2-3.",
        description_why="Triads are the building blocks of all chords. Knowing them everywhere opens up endless voicings.",
        steps=["Learn root position triad", "Learn 1st inversion", "Learn 2nd inversion", "Connect shapes up the neck"],
        mistakes_and_fixes=["Not visualizing - Say note names while playing", "Shapes blurring together - Color-code inversions mentally"],
        success_criteria={"shape_knowledge": 85, "fluency": 80}
    ),
]

# Scale Exercises
SCALE_EXERCISES = [
    Exercise(
        id="scale-001",
        title="Minor Pentatonic Box 1",
        domain=SkillDomain.SCALES,
        subdomain="Pentatonic",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=180,
        bpm_start=50,
        bpm_target=90,
        tags=["pentatonic", "minor", "essential", "box-1"],
        description_training="Learn the most important scale pattern in guitar.",
        description_why="Minor pentatonic box 1 is used in rock, blues, and pop more than any other pattern.",
        steps=["Learn pattern starting on fret 5 (Am)", "Descend and ascend", "Use alternate picking", "Feel the bluesy sound"],
        mistakes_and_fixes=["Skipping notes - Practice slowly with metronome", "No musicality - Add vibrato on long notes"],
        success_criteria={"accuracy": 95, "speed": 80},
        tab_data=generate_tab_data([{"fret": 5, "string": 5}, {"fret": 8, "string": 5}, {"fret": 5, "string": 4}, {"fret": 7, "string": 4}, {"fret": 5, "string": 3}, {"fret": 7, "string": 3}])
    ),
    Exercise(
        id="scale-002",
        title="Minor Pentatonic Box 2",
        domain=SkillDomain.SCALES,
        subdomain="Pentatonic",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=180,
        bpm_start=50,
        bpm_target=85,
        tags=["pentatonic", "minor", "box-2"],
        description_training="Add the second pentatonic position to your vocabulary.",
        description_why="Box 2 connects to box 1 and starts expanding your fretboard range.",
        steps=["Learn pattern at fret 8 (Am)", "Note how it connects to box 1", "Practice ascending and descending", "Find common notes between boxes"],
        mistakes_and_fixes=["Losing position - Use fret markers as reference", "Can't connect to box 1 - Practice transition notes"],
        success_criteria={"accuracy": 90, "connection": 80}
    ),
    Exercise(
        id="scale-003",
        title="Blues Scale",
        domain=SkillDomain.SCALES,
        subdomain="Blues",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=180,
        bpm_start=50,
        bpm_target=85,
        tags=["blues", "scale", "blue-note"],
        description_training="Add the blue note to minor pentatonic.",
        description_why="The blue note (b5) adds tension and character that defines the blues sound.",
        steps=["Start with minor pentatonic box 1", "Add note between 4th and 5th", "Feel the tension of blue note", "Resolve to root or 5th"],
        mistakes_and_fixes=["Blue note sounds wrong - Don't stay on it too long", "Missing the note - Practice chromatic run through it"],
        success_criteria={"accuracy": 90, "expression": 80}
    ),
    Exercise(
        id="scale-004",
        title="Major Scale Position 1",
        domain=SkillDomain.SCALES,
        subdomain="Major",
        difficulty_tier=DifficultyTier.INTERMEDIATE,
        duration_seconds=180,
        bpm_start=50,
        bpm_target=80,
        tags=["major", "scale", "theory"],
        description_training="Learn the foundational major scale pattern.",
        description_why="The major scale is the mother of all Western music theory. Everything relates back to it.",
        steps=["Learn C major at open position", "Or G major at fret 2", "3-note-per-string not needed yet", "Feel the bright, happy sound"],
        mistakes_and_fixes=["Sounds 'wrong' after pentatonic - That's the full scale, embrace it", "Finger stretch issues - Use comfortable position"],
        success_criteria={"accuracy": 90, "musicality": 80}
    ),
    Exercise(
        id="scale-005",
        title="Natural Minor Scale",
        domain=SkillDomain.SCALES,
        subdomain="Minor",
        difficulty_tier=DifficultyTier.INTERMEDIATE,
        duration_seconds=180,
        bpm_start=50,
        bpm_target=80,
        tags=["natural-minor", "scale", "emotional"],
        description_training="Complete the minor scale beyond pentatonic.",
        description_why="Natural minor has 7 notes versus pentatonic's 5, giving more melodic options.",
        steps=["Start with minor pentatonic", "Add the 2nd and 6th degrees", "Practice in Am at fret 5", "Compare sound to major scale"],
        mistakes_and_fixes=["Can't hear the difference - Play major then minor back to back", "New notes feel awkward - Isolate them in short patterns"],
        success_criteria={"accuracy": 90, "differentiation": 85}
    ),
    Exercise(
        id="scale-006",
        title="Connecting Pentatonic Boxes",
        domain=SkillDomain.SCALES,
        subdomain="Fretboard Navigation",
        difficulty_tier=DifficultyTier.INTERMEDIATE,
        duration_seconds=240,
        bpm_start=40,
        bpm_target=70,
        tags=["pentatonic", "connection", "fretboard"],
        description_training="Link all 5 pentatonic boxes together.",
        description_why="Connecting boxes means you can solo anywhere on the neck, not just one position.",
        steps=["Learn all 5 box patterns", "Find linking notes between each", "Practice sequences that span boxes", "Eventually see one big pattern"],
        mistakes_and_fixes=["Getting lost between boxes - Use backing track, find root", "Boxes feel separate - Practice sliding between them"],
        success_criteria={"navigation": 80, "continuity": 80}
    ),
    Exercise(
        id="scale-007",
        title="Modes Introduction: Dorian",
        domain=SkillDomain.SCALES,
        subdomain="Modes",
        difficulty_tier=DifficultyTier.ADVANCED,
        duration_seconds=240,
        bpm_start=50,
        bpm_target=75,
        tags=["modes", "dorian", "jazz"],
        description_training="Explore the Dorian mode sound and application.",
        description_why="Dorian is the most used mode in jazz and fusion. Its minor sound with raised 6th is distinctive.",
        steps=["Play D Dorian (D to D on C major scale)", "Note the raised 6th compared to natural minor", "Play over a Dm7 chord", "Feel the jazzy sound"],
        mistakes_and_fixes=["Sounds like C major - Emphasize D as home base", "Can't hear the difference - Compare to D natural minor"],
        success_criteria={"sound_recognition": 80, "application": 75}
    ),
]

# Lead/Punteos Exercises
LEAD_EXERCISES = [
    Exercise(
        id="lead-001",
        title="Two-Note Phrases",
        domain=SkillDomain.LEAD,
        subdomain="Phrasing",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=180,
        bpm_start=60,
        bpm_target=90,
        tags=["phrasing", "melody", "basics"],
        description_training="Create musical phrases with just two notes.",
        description_why="Great solos are built from simple phrases. Two notes can be incredibly expressive.",
        steps=["Choose any two pentatonic notes", "Vary rhythm between them", "Add dynamics (loud/soft)", "Create call and response"],
        mistakes_and_fixes=["Playing too many notes - Embrace space", "Mechanical feel - Add vibrato, vary attack"],
        success_criteria={"musicality": 80, "expression": 85}
    ),
    Exercise(
        id="lead-002",
        title="Four-Note Sequence",
        domain=SkillDomain.LEAD,
        subdomain="Sequences",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=180,
        bpm_start=50,
        bpm_target=85,
        tags=["sequence", "pattern", "foundation"],
        description_training="Master the classic 4-note sequence up and down scales.",
        description_why="Sequences are building blocks of solos. They train both hands and musical ear.",
        steps=["Play notes 1-2-3-4 of scale", "Then 2-3-4-5", "Continue up the scale", "Reverse going down"],
        mistakes_and_fixes=["Rushing - Keep strict timing with metronome", "Missing notes - Slow down, accuracy first"],
        success_criteria={"accuracy": 90, "evenness": 85}
    ),
    Exercise(
        id="lead-003",
        title="Pentatonic Lick 1: Classic Rock",
        domain=SkillDomain.LEAD,
        subdomain="Licks",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=180,
        bpm_start=60,
        bpm_target=100,
        tags=["lick", "rock", "classic"],
        description_training="Learn your first essential pentatonic lick.",
        description_why="Licks are pre-made phrases you can use in solos. This one appears in countless rock songs.",
        steps=["Start on root note", "Bend up from below", "Return to root", "Add vibrato on final note"],
        mistakes_and_fixes=["Bend out of tune - Check target pitch", "No sustain - Keep pressure through bend"],
        success_criteria={"accuracy": 85, "feel": 80}
    ),
    Exercise(
        id="lead-004",
        title="Target Note Soloing",
        domain=SkillDomain.LEAD,
        subdomain="Improvisation",
        difficulty_tier=DifficultyTier.INTERMEDIATE,
        duration_seconds=240,
        bpm_start=60,
        bpm_target=90,
        tags=["target-notes", "chord-tones", "soloing"],
        description_training="Land on chord tones when chords change.",
        description_why="Targeting chord tones makes your solos sound like they belong with the chords.",
        steps=["Identify root note of each chord", "Aim to land on root on beat 1", "Fill space between targets", "Expand to 3rds and 5ths"],
        mistakes_and_fixes=["Missing the change - Listen ahead to backing track", "Landing on wrong note - Study chord progression first"],
        success_criteria={"accuracy": 80, "musicality": 85}
    ),
    Exercise(
        id="lead-005",
        title="Call and Response",
        domain=SkillDomain.LEAD,
        subdomain="Phrasing",
        difficulty_tier=DifficultyTier.INTERMEDIATE,
        duration_seconds=240,
        bpm_start=60,
        bpm_target=85,
        tags=["call-response", "blues", "phrasing"],
        description_training="Create conversational phrases in your solos.",
        description_why="Call and response is the oldest form of musical dialogue. It creates tension and resolution.",
        steps=["Play a short 'question' phrase", "Answer with a related phrase", "Vary the responses", "Leave space for 'breathing'"],
        mistakes_and_fixes=["Phrases sound unrelated - Use similar rhythms", "No breathing room - Count rest beats out loud"],
        success_criteria={"musicality": 85, "phrasing": 80}
    ),
    Exercise(
        id="lead-006",
        title="Speed Lick Building",
        domain=SkillDomain.LEAD,
        subdomain="Speed",
        difficulty_tier=DifficultyTier.ADVANCED,
        duration_seconds=240,
        bpm_start=60,
        bpm_target=140,
        tags=["speed", "technique", "advanced"],
        description_training="Build a fast lick from slow to performance speed.",
        description_why="Speed comes from correct slow practice. This method builds reliable fast playing.",
        steps=["Learn lick perfectly at 60 BPM", "Increase by 5 BPM when clean", "If mistakes, drop 10 BPM", "Never sacrifice accuracy for speed"],
        mistakes_and_fixes=["Plateauing - Try burst practice (short fast, return to slow)", "Tension buildup - Reset hands every 2 minutes"],
        success_criteria={"speed": 130, "accuracy": 90}
    ),
]

# Techniques Exercises
TECHNIQUE_EXERCISES = [
    Exercise(
        id="tech-001",
        title="Hammer-On Basics",
        domain=SkillDomain.TECHNIQUES,
        subdomain="Hammer-On",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=120,
        bpm_start=50,
        bpm_target=90,
        tags=["hammer-on", "legato", "essential"],
        description_training="Develop strong hammer-on technique.",
        description_why="Hammer-ons create smooth legato sound and let you play faster with less picking.",
        steps=["Play open string", "Hammer finger down firmly", "Second note should ring clearly", "Don't re-pick the second note"],
        mistakes_and_fixes=["Second note too quiet - Hammer harder, closer to fret", "Accidentally muting - Keep other fingers clear"],
        success_criteria={"volume_balance": 85, "clarity": 90}
    ),
    Exercise(
        id="tech-002",
        title="Pull-Off Basics",
        domain=SkillDomain.TECHNIQUES,
        subdomain="Pull-Off",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=120,
        bpm_start=50,
        bpm_target=90,
        tags=["pull-off", "legato", "essential"],
        description_training="Master the pull-off motion.",
        description_why="Pull-offs complete the legato vocabulary and are essential for fluid playing.",
        steps=["Fret two notes on same string", "Pick the higher note", "Pull finger down and slightly off", "Lower note should ring"],
        mistakes_and_fixes=["Lower note doesn't sound - Pull downward, not just lift", "String snapping - Less aggressive pull"],
        success_criteria={"volume_balance": 85, "clarity": 90}
    ),
    Exercise(
        id="tech-003",
        title="Basic Slides",
        domain=SkillDomain.TECHNIQUES,
        subdomain="Slides",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=120,
        bpm_start=50,
        bpm_target=85,
        tags=["slides", "legato", "expression"],
        description_training="Perform smooth slides between frets.",
        description_why="Slides add emotion and connect notes in ways that picking can't match.",
        steps=["Fret a note", "Maintain pressure while sliding to target", "Don't lift finger during slide", "Control slide speed"],
        mistakes_and_fixes=["Note dying during slide - Keep constant pressure", "Overshooting target - Practice specific distances"],
        success_criteria={"smoothness": 85, "accuracy": 85}
    ),
    Exercise(
        id="tech-004",
        title="Basic Vibrato",
        domain=SkillDomain.TECHNIQUES,
        subdomain="Vibrato",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=180,
        bpm_start=50,
        bpm_target=75,
        tags=["vibrato", "expression", "essential"],
        description_training="Develop controlled vibrato technique.",
        description_why="Vibrato is your personal sound signature. It makes notes sing and adds emotion.",
        steps=["Fret a note", "Rotate wrist slightly back and forth", "Keep movement even and controlled", "Vary speed for different feels"],
        mistakes_and_fixes=["Too fast/nervous sounding - Slow down, relax", "Uneven wobble - Practice with metronome"],
        success_criteria={"evenness": 80, "control": 85}
    ),
    Exercise(
        id="tech-005",
        title="Whole Step Bends",
        domain=SkillDomain.TECHNIQUES,
        subdomain="Bending",
        difficulty_tier=DifficultyTier.INTERMEDIATE,
        duration_seconds=180,
        bpm_start=50,
        bpm_target=80,
        tags=["bending", "expression", "essential"],
        description_training="Master the critical whole step bend.",
        description_why="Bends are the most expressive guitar technique. Accurate bends separate good from great.",
        steps=["Play target note first (2 frets up)", "Bend from 2 frets below to match pitch", "Use multiple fingers to support", "Push toward ceiling (not pull)"],
        mistakes_and_fixes=["Bend out of tune - Always check target pitch first", "Finger slipping - Use more supporting fingers"],
        success_criteria={"pitch_accuracy": 90, "sustain": 80}
    ),
    Exercise(
        id="tech-006",
        title="Palm Muting Basics",
        domain=SkillDomain.TECHNIQUES,
        subdomain="Palm Muting",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=120,
        bpm_start=60,
        bpm_target=100,
        tags=["palm-mute", "rock", "metal"],
        description_training="Control palm muting for rhythm guitar.",
        description_why="Palm muting creates the chugging sound in rock and metal. Essential for rhythm guitar.",
        steps=["Rest palm edge on strings near bridge", "Adjust position for desired dampening", "Pick through the mute", "Experiment with mute placement"],
        mistakes_and_fixes=["Too muted/dead sound - Move palm toward neck", "Not muted enough - Move palm toward bridge"],
        success_criteria={"consistency": 90, "tone_control": 85}
    ),
    Exercise(
        id="tech-007",
        title="Hammer-On Pull-Off Combos",
        domain=SkillDomain.TECHNIQUES,
        subdomain="Legato",
        difficulty_tier=DifficultyTier.INTERMEDIATE,
        duration_seconds=180,
        bpm_start=50,
        bpm_target=95,
        tags=["legato", "combination", "fluidity"],
        description_training="Combine hammer-ons and pull-offs fluidly.",
        description_why="Legato combinations create smooth, fast lines with minimal picking.",
        steps=["Pick first note only", "Hammer to next note", "Pull off back to first", "Create triplet feel: pick-hammer-pull"],
        mistakes_and_fixes=["Volume dropping off - Build finger strength", "Notes running together - Cleaner articulation"],
        success_criteria={"evenness": 85, "speed": 85}
    ),
    Exercise(
        id="tech-008",
        title="Bend and Release",
        domain=SkillDomain.TECHNIQUES,
        subdomain="Bending",
        difficulty_tier=DifficultyTier.INTERMEDIATE,
        duration_seconds=180,
        bpm_start=40,
        bpm_target=70,
        tags=["bending", "expression", "control"],
        description_training="Control bend up and return down.",
        description_why="Controlled release is as important as the bend up. This creates singing melodic lines.",
        steps=["Bend up to target pitch", "Hold at top", "Release slowly back to original", "Keep note ringing throughout"],
        mistakes_and_fixes=["Note dying during release - Maintain pressure", "Pitch wobbling - Build forearm strength"],
        success_criteria={"pitch_control": 85, "sustain": 80}
    ),
    Exercise(
        id="tech-009",
        title="Tapping Introduction",
        domain=SkillDomain.TECHNIQUES,
        subdomain="Tapping",
        difficulty_tier=DifficultyTier.ADVANCED,
        duration_seconds=240,
        bpm_start=40,
        bpm_target=80,
        tags=["tapping", "two-hand", "advanced"],
        description_training="Learn basic two-hand tapping technique.",
        description_why="Tapping extends your range dramatically and creates pianistic arpeggios on guitar.",
        steps=["Fret note with left hand", "Tap higher fret with right index finger", "Pull off to left hand note", "Create smooth pattern"],
        mistakes_and_fixes=["Tapped note too quiet - Tap firmly, close to fret", "Extra noise - Mute unused strings with available fingers"],
        success_criteria={"volume_balance": 80, "clarity": 80}
    ),
]

# Musical Application Exercises
APPLICATION_EXERCISES = [
    Exercise(
        id="app-001",
        title="12-Bar Blues Rhythm",
        domain=SkillDomain.MUSICAL_APPLICATION,
        subdomain="Blues",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=240,
        bpm_start=70,
        bpm_target=100,
        tags=["blues", "rhythm", "form"],
        description_training="Play the classic 12-bar blues progression.",
        description_why="12-bar blues is the foundation of rock, jazz, and pop. Every guitarist must know it.",
        steps=["I chord for 4 bars (e.g., A)", "IV chord for 2 bars (D)", "I chord for 2 bars (A)", "V-IV-I-V turnaround"],
        mistakes_and_fixes=["Losing the form - Count bars out loud", "Changes feel rushed - Feel the form, anticipate changes"],
        success_criteria={"form_accuracy": 95, "groove": 85}
    ),
    Exercise(
        id="app-002",
        title="Rock Riff Pattern",
        domain=SkillDomain.MUSICAL_APPLICATION,
        subdomain="Rock",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=180,
        bpm_start=80,
        bpm_target=120,
        tags=["rock", "riff", "electric"],
        description_training="Learn a classic rock-style riff pattern.",
        description_why="Riffs are the memorable hooks that define rock songs. Learning patterns trains riff writing.",
        steps=["Start with power chord root", "Add single note fills", "Use palm muting for punch", "Lock with imaginary drums"],
        mistakes_and_fixes=["Riff sounds weak - Add more palm muting", "Timing loose - Play with drum track"],
        success_criteria={"tightness": 90, "power": 85}
    ),
    Exercise(
        id="app-003",
        title="Folk Fingerpicking Pattern",
        domain=SkillDomain.MUSICAL_APPLICATION,
        subdomain="Folk",
        difficulty_tier=DifficultyTier.INTERMEDIATE,
        duration_seconds=240,
        bpm_start=50,
        bpm_target=80,
        tags=["fingerpicking", "folk", "acoustic"],
        description_training="Master the Travis picking pattern.",
        description_why="Travis picking is essential for folk, country, and singer-songwriter styles.",
        steps=["Thumb plays bass notes on 1 and 3", "Fingers play treble on 2 and 4", "Maintain alternating bass", "Add chord changes"],
        mistakes_and_fixes=["Bass and treble collision - Slow down, separate parts", "Losing alternating bass - Practice bass alone first"],
        success_criteria={"independence": 80, "steadiness": 85}
    ),
    Exercise(
        id="app-004",
        title="Funk Rhythm Guitar",
        domain=SkillDomain.MUSICAL_APPLICATION,
        subdomain="Funk",
        difficulty_tier=DifficultyTier.INTERMEDIATE,
        duration_seconds=240,
        bpm_start=80,
        bpm_target=110,
        tags=["funk", "rhythm", "groove"],
        description_training="Develop funky sixteenth-note rhythm patterns.",
        description_why="Funk guitar is all about precise rhythm and pocket. It trains your timing like nothing else.",
        steps=["Constant sixteenth strumming motion", "Add ghost strums and scratches", "Accent on off-beats", "Stay super relaxed"],
        mistakes_and_fixes=["Too stiff - Loosen grip, shake out hands", "Losing pocket - Listen to hi-hat in track"],
        success_criteria={"groove": 85, "consistency": 90}
    ),
    Exercise(
        id="app-005",
        title="Pop Chord Progression",
        domain=SkillDomain.MUSICAL_APPLICATION,
        subdomain="Pop",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=180,
        bpm_start=70,
        bpm_target=100,
        tags=["pop", "chords", "songwriting"],
        description_training="Play the I-V-vi-IV pop progression.",
        description_why="This progression appears in hundreds of hit songs. It's essential musical vocabulary.",
        steps=["Play G-D-Em-C (in G)", "Or C-G-Am-F (in C)", "4 beats per chord", "Add your strumming pattern"],
        mistakes_and_fixes=["Changes too slow - Simplify strumming", "Sounds mechanical - Vary dynamics per chord"],
        success_criteria={"smoothness": 90, "musicality": 85}
    ),
]

# Improvisation Exercises
IMPROV_EXERCISES = [
    Exercise(
        id="improv-001",
        title="One-Note Solo",
        domain=SkillDomain.IMPROVISATION,
        subdomain="Guided",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=180,
        bpm_start=60,
        bpm_target=85,
        tags=["improvisation", "basics", "rhythm"],
        description_training="Solo using only one note and rhythm.",
        description_why="Limitation breeds creativity. This exercise proves melody isn't about many notes.",
        steps=["Choose one pentatonic note", "Vary only the rhythm", "Play over backing track", "Find how musical one note can be"],
        mistakes_and_fixes=["Adding extra notes - Reset, commit to limitation", "Running out of ideas - Try longer/shorter rhythms"],
        success_criteria={"creativity": 80, "rhythm_variety": 85}
    ),
    Exercise(
        id="improv-002",
        title="Three-Note Melody",
        domain=SkillDomain.IMPROVISATION,
        subdomain="Guided",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=180,
        bpm_start=60,
        bpm_target=85,
        tags=["improvisation", "melody", "basics"],
        description_training="Create melodies with only three notes.",
        description_why="Great hooks often use just three notes. Learn to maximize minimal material.",
        steps=["Choose 3 adjacent pentatonic notes", "Create a melody", "Repeat with variations", "Find your favorite pattern"],
        mistakes_and_fixes=["Melody has no shape - Think verse/chorus in miniature", "All notes equal - Create a 'star' note that appears more"],
        success_criteria={"melodic_interest": 80, "phrasing": 80}
    ),
    Exercise(
        id="improv-003",
        title="Pentatonic Box 1 Free Play",
        domain=SkillDomain.IMPROVISATION,
        subdomain="Semi-Guided",
        difficulty_tier=DifficultyTier.BEGINNER,
        duration_seconds=240,
        bpm_start=60,
        bpm_target=90,
        tags=["improvisation", "pentatonic", "freedom"],
        description_training="Free improvisation within pentatonic box 1.",
        description_why="After learning the notes, you need to play freely to internalize them.",
        steps=["Play over backing track", "Stay within box 1", "Don't judge, just play", "Focus on rhythm and feel"],
        mistakes_and_fixes=["Playing scales up and down - Focus on phrases, not patterns", "Mind going blank - Return to simple rhythms"],
        success_criteria={"freedom": 75, "musicality": 75}
    ),
    Exercise(
        id="improv-004",
        title="Chord Tone Targeting",
        domain=SkillDomain.IMPROVISATION,
        subdomain="Semi-Guided",
        difficulty_tier=DifficultyTier.INTERMEDIATE,
        duration_seconds=300,
        bpm_start=60,
        bpm_target=80,
        tags=["improvisation", "chord-tones", "theory"],
        description_training="Target chord tones during chord changes.",
        description_why="Targeting chord tones makes your solos connect with the harmony.",
        steps=["Know the chords in backing track", "Land on root when chord changes", "Expand to 3rds and 5ths", "Fill between targets freely"],
        mistakes_and_fixes=["Missing changes - Watch/feel the form", "Landing feels random - Study chord tones before playing"],
        success_criteria={"targeting": 80, "musicality": 80}
    ),
    Exercise(
        id="improv-005",
        title="Full Neck Exploration",
        domain=SkillDomain.IMPROVISATION,
        subdomain="Free",
        difficulty_tier=DifficultyTier.ADVANCED,
        duration_seconds=360,
        bpm_start=60,
        bpm_target=85,
        tags=["improvisation", "fretboard", "advanced"],
        description_training="Solo across the entire fretboard.",
        description_why="Professional soloists use the whole neck. This builds that capability.",
        steps=["Start in any position", "Move up or down neck every 2 bars", "Connect boxes smoothly", "Develop position awareness"],
        mistakes_and_fixes=["Getting stuck in boxes - Force yourself to slide", "Losing track of root - Practice finding root anywhere"],
        success_criteria={"navigation": 80, "continuity": 80}
    ),
]

# Combine all exercises
ALL_EXERCISES = (
    TIMING_EXERCISES +
    STRUMMING_EXERCISES +
    PICKING_EXERCISES +
    FRETTING_EXERCISES +
    CHORD_EXERCISES +
    SCALE_EXERCISES +
    LEAD_EXERCISES +
    TECHNIQUE_EXERCISES +
    APPLICATION_EXERCISES +
    IMPROV_EXERCISES
)

def get_all_exercises():
    """Return all seed exercises as dictionaries."""
    return [ex.dict() for ex in ALL_EXERCISES]

def get_exercises_by_domain(domain: SkillDomain):
    """Get exercises filtered by domain."""
    return [ex.dict() for ex in ALL_EXERCISES if ex.domain == domain]

def get_exercises_by_difficulty(tier: DifficultyTier):
    """Get exercises filtered by difficulty."""
    return [ex.dict() for ex in ALL_EXERCISES if ex.difficulty_tier == tier]

if __name__ == "__main__":
    print(f"Total exercises: {len(ALL_EXERCISES)}")
    for domain in SkillDomain:
        count = len([ex for ex in ALL_EXERCISES if ex.domain == domain])
        print(f"  {domain.value}: {count}")
